#!/usr/bin/env python3
"""
Cache-Busting bump tool — Zero Hard-Reload.

Usage:  python3 tools/bump_version.py 6.0

What it does (all inside app/):
  1. Writes app/js/core/version.js      -> export const APP_VERSION = '6.0'
  2. Writes app/version.json            -> {"v":"6.0","ts":...}
  3. Rewrites index.html:
       - every local css/js href/src gets ?v=6.0
       - regenerates <script type="importmap"> mapping EVERY module URL in
         app/js/** to its versioned URL, so the whole ES-module graph is
         busted without touching a single import statement.
"""
import json, os, re, sys, time

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
APP = os.path.join(ROOT, 'app')
INDEX = os.path.join(APP, 'index.html')
JS_DIR = os.path.join(APP, 'js')


def list_modules():
    out = []
    for dp, _, fns in os.walk(JS_DIR):
        for fn in fns:
            if fn.endswith('.js'):
                rel = os.path.relpath(os.path.join(dp, fn), APP).replace(os.sep, '/')
                out.append('./' + rel)
    return sorted(out)


def build_importmap(v):
    imports = {m: f'{m}?v={v}' for m in list_modules()}
    body = json.dumps({'imports': imports}, ensure_ascii=False, indent=2)
    return f'<script type="importmap" data-v="{v}">\n{body}\n</script>'


def bump(v):
    # 1. version.js
    with open(os.path.join(JS_DIR, 'core', 'version.js'), 'w', encoding='utf-8') as f:
        f.write(f"/** Auto-generated by tools/bump_version.py — do not edit by hand. */\nexport const APP_VERSION = '{v}';\nexport default APP_VERSION;\n")
    # 2. version.json
    with open(os.path.join(APP, 'version.json'), 'w', encoding='utf-8') as f:
        json.dump({'v': v, 'ts': int(time.time())}, f)
    # 3. index.html
    html = open(INDEX, encoding='utf-8').read()
    # strip old ?v= on local assets, then add new
    html = re.sub(r'((?:href|src)=")((?:css|js)/[^"?]+)(?:\?v=[^"]*)?"', lambda m: f'{m.group(1)}{m.group(2)}?v={v}"', html)
    # importmap (replace or insert before first module script)
    im = build_importmap(v)
    if re.search(r'<script type="importmap"[^>]*>.*?</script>', html, flags=re.S):
        html = re.sub(r'<script type="importmap"[^>]*>.*?</script>', lambda _: im, html, flags=re.S)
    else:
        html = html.replace('  <script type="module"', '  ' + im + '\n  <script type="module"', 1)
    open(INDEX, 'w', encoding='utf-8').write(html)
    print(f'bumped to v{v}: {len(list_modules())} modules mapped')


if __name__ == '__main__':
    if len(sys.argv) < 2:
        print(__doc__); sys.exit(1)
    bump(sys.argv[1])
